namespace OneMind.Requests;

public record SendUserAutoGeneratedPasswordToEmailAddressRequest : IRequest<Guid>
{
    public string EmailAddress { get; init; } = "";
    public string Password { get; init; } = "";
}