namespace OneMind.Handlers;

sealed class SignupUserWithEmailAddressHandler : IRequestHandler<SignupUserWithEmailAddressRequest, int>
{
    readonly IDbContextFactory<OneMindDbContext> _contextFactory;
    readonly InsertUser _insertUser;
    readonly IUserPasswordCryptoService _passwordCryptoService;
    readonly IMediator _mediator;
    readonly IUsernameFromEmailAddressExtractor _usernameFromEmailAddressExtractor;
    readonly IUserPasswordGenerator _passwordGenerator;

    public SignupUserWithEmailAddressHandler(IDbContextFactory<OneMindDbContext> contextFactory, InsertUser insertUser, IUserPasswordCryptoService passwordCryptoService, IMediator mediator, IUsernameFromEmailAddressExtractor usernameFromEmailAddressExtractor, IUserPasswordGenerator passwordGenerator)
    {
        _contextFactory = contextFactory;
        _insertUser = insertUser;
        _passwordCryptoService = passwordCryptoService;
        _mediator = mediator;
        _usernameFromEmailAddressExtractor = usernameFromEmailAddressExtractor;
        _passwordGenerator = passwordGenerator;
    }

    public async Task<int> Handle(SignupUserWithEmailAddressRequest request, CancellationToken cancellationToken)
    {
        using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        using var transaction = await context.Database.BeginTransactionAsync(cancellationToken);

        var username = _usernameFromEmailAddressExtractor.Extract(request.EmailAddress);
        var password = _passwordGenerator.Generate();

        var id = await _insertUser.ExecuteAsync(
            context.WithHotSave(),
            new()
            {
                Username = username,
                EmailAddress = request.EmailAddress,
                HashedPassword = _passwordCryptoService.ComputeHash(password),
                IsEmailVerified = false,
                IsPasswordChangeRequired = false,
            }
        );

        if (id != 0)
        {
            var sendUserAutoGeneratedPasswordToEmailRequest = new SendUserAutoGeneratedPasswordToEmailAddressRequest
            {
                EmailAddress = request.EmailAddress,
                Password = password
            };

            var sendUserEmailVerificationRequest = new SendUserEmailVerificationRequest
            {
                Id = id,
                EmailAddress = request.EmailAddress
            };

            await _mediator.Send(sendUserAutoGeneratedPasswordToEmailRequest, cancellationToken);
            await _mediator.Send(sendUserEmailVerificationRequest, cancellationToken);
            await _mediator.Publish(new UserCreated { Id = id }, cancellationToken);
        }

        await transaction.CommitAsync(cancellationToken);
        return id;
    }
}
